[Add] partner app started, created classes in partner.models.py.(didn…
wecode-bootcamp-korea/9-controst-backend pull request #1
Opened 2020-06-24 15:25 UTC by Einsicht1

…'t make migrations yet). created db_uploader.py and csv file where manage.py is in

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
파트너 앱 생성, models.py에 클래스 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
-파트너 앱 생성, models.pyd에 클래스들 생성(미완성, makemigrations하지 않았음.)
-db_uploader.py와 csv파일을  manage.py가 있는 디렉토리에 추가.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ v] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ v] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ v] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-06-25 06:11 UTC, devops-andrew requested changes

2020-06-25 06:11 UTC, ulfrid commented on db_uploader.py
> +#    for row in data_reader:
가급적 업로더는 깃에 추가하지 말아주세요.

2020-06-25 06:11 UTC, ulfrid commented on partner/models.py
> +    gender = models.IntegerField(choices=GENDER_CHOICES)
장고 어드민이거나, 장고에서 바로 페이징하는 경우 문제되지 않는 구현 방식이지만, api로써는 이방식은 적절하지 않습니다.
프론트에서 CHOICE요소를 어떻게 알수 있죠? 
이렇게 해야한다면 gender라는 테이블을 만들고 OneToOne 해야할것 입니다.
그렇게 까지 해야하지 않는다면, CharField선언해서, 문자로 받으세요.

2020-06-25 06:11 UTC, ulfrid commented on partner/models.py
> +    level = models.CharFIeld(max_length=20)
```suggestion
    name = models.CharFIeld(max_length=20)
```
레벨이라는건 테이블이 말해주고있습니다.

2020-06-25 06:11 UTC, ulfrid commented on partner/models.py
> +    profile_image_url = models.URLField(max_length=200)
```suggestion
    profile_image_url = models.URLField(max_length=2000)
```

2020-06-25 06:11 UTC, ulfrid commented on partner/models.py
> +    counsel_themes = models.ManyToManyField(Theme)
through 해주세요.

2020-06-25 06:11 UTC, ulfrid commented on partner/models.py
> +    counsel_kinds = models.ManyToManyField(Counsel_Kind)
through해주세요.

2020-06-25 06:11 UTC, ulfrid commented on partner/models.py
> +    price = models.IntegerField(deafult=0)
```suggestion
    price = models.DecimalField(max_digits=12, decimal_places=2)
```
통화는 1000.00원 같이 관리해주세요. DecimalField를 사용해주세요.

2020-06-25 14:14 UTC, Einsicht1 commented on partner/models.py
> +    price = models.IntegerField(deafult=0)
완료했습니다!

2020-06-25 14:14 UTC, Einsicht1 commented on partner/models.py
> +    counsel_kinds = models.ManyToManyField(Counsel_Kind)
수정반영 했습니다.

2020-06-25 14:14 UTC, Einsicht1 commented on partner/models.py
> +    profile_image_url = models.URLField(max_length=200)
수정반영 했습니다.

2020-06-25 14:14 UTC, Einsicht1 commented on partner/models.py
> +    level = models.CharFIeld(max_length=20)
수정반영 했습니다.

2020-06-25 14:14 UTC, Einsicht1 commented on partner/models.py
> +    gender = models.IntegerField(choices=GENDER_CHOICES)
수정반영 했습니다.

2020-06-25 14:15 UTC, Einsicht1 commented on db_uploader.py
> +#    for row in data_reader:
수정반영 했습니다.

2020-06-26 01:46 UTC, evergreen-david requested changes

2020-06-26 01:46 UTC, evergreen-david commented on partner/models.py
> +    name = models.CharField(max_length=19)
굳이 홀수로 한이유가있을까요 ? max_length 20으로해도될것같아요

2020-06-26 01:46 UTC, evergreen-david commented on partner/models.py
> +    is_counsel_gt_150 = models.IntegerField(default=0)
필드전체 = 기준으로 정렬 해주세요. 
```suggestion
    introduction      = models.CharField(max_length=1000)
    is_counsel_gt_150 = models.IntegerField(default=0)
```

2020-06-26 02:14 UTC, evergreen-david requested changes

2020-06-26 02:14 UTC, evergreen-david commented on partner/models.py
> +        db_table = "durations"
durations 라는거는 없기때문에 duration 으로 고쳐주시겠어요?

2020-06-26 02:14 UTC, evergreen-david commented on partner/models.py
> +
파일의 끝 은 한줄만 띄우도록 부탁 드립니다.

2020-06-26 02:15 UTC, evergreen-david requested changes

2020-06-26 02:15 UTC, evergreen-david commented on partner/models.py
> +    is_counsel_gt_150 = models.IntegerField(default=0)
is 인데 boolean 아닌가요 ? 
```suggestion
    is_counsel_gt_150 = models.IntegerField(default=0)
```

2020-06-26 02:15 UTC, evergreen-david commented on partner/models.py
> +    is_counsel_gt_150 = models.IntegerField(default=0)
그리고 is_ counsel_count_gt_150 이라고 하는게 나을것같습니다.

2020-06-26 02:24 UTC, evergreen-david approved these changes

2020-06-26 02:24 UTC, evergreen-david commented on partner/models.py
> +
한줄 지워주세요.

2020-06-26 02:25 UTC, evergreen-david commented
LGTM

2020-06-26 02:25 UTC, merged