Feature/partner listup
wecode-bootcamp-korea/9-controst-backend pull request #4
Opened 2020-06-29 14:23 UTC by Einsicht1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
  partner앱 views구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
1)partner앱 views구현
2)mainurl->partner.urls include시킴.
3>앱이름 변경(users->user)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [v ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ v] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ v] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-06-30 10:01 UTC, evergreen-david requested changes

2020-06-30 10:01 UTC, evergreen-david commented on partner/urls.py
> +        ]
```suggestion
]
```

2020-06-30 10:01 UTC, evergreen-david commented on partner/urls.py
> +        path('', ListUp.as_view()),
```suggestion
    path('', ListUp.as_view()),
```

2020-06-30 10:01 UTC, evergreen-david commented on partner/views.py
> +        )
```suggestion
)
```

2020-06-30 10:01 UTC, evergreen-david commented on partner/views.py
> +        Product
들여쓰기 4칸으로 정리 부탁 드립니다.

2020-06-30 10:01 UTC, evergreen-david commented on partner/views.py
> +                prices_list.append(price.price)
리스트 컴프리헨션으로 바꿔보세요.

2020-06-30 10:01 UTC, evergreen-david commented on trost/settings.py
> +ALLOWED_HOSTS = ['*',"10.58.7.28", "10.58.7.28:8000"]
ip노출은 지양해주세요.

2020-06-30 10:04 UTC, evergreen-david requested changes

2020-06-30 10:04 UTC, evergreen-david commented on trost/urls.py
> +   path('partner', include('partner.urls')),
22라인 주석은 정리해주세요.

2020-06-30 10:04 UTC, evergreen-david commented on trost/urls.py
> +        include)
```suggestion
    path,
    include
)
```

2020-06-30 10:08 UTC, evergreen-david requested changes

2020-06-30 10:08 UTC, evergreen-david commented on partner/views.py
> +            partners_list.append(
가독성과 성능을 위해서 partners_list도 리스트 컴프리헨션으로 작성해주세요.

2020-06-30 10:08 UTC, evergreen-david commented on partner/views.py
> +            review_count=Review.objects.filter(history__in=partner.history_set.all()).count()
```suggestion
            review_count = Review.objects.filter(history__in=partner.history_set.all()).count()
```

2020-06-30 16:13 UTC, soheon-lee commented on partner/views.py
> +        products = Product.objects.all()
`products`는 사용하지 않는 것으로 보이는데 호출하신 특별한 이유가 있나요?

2020-07-01 01:25 UTC, soheon-lee commented on partner/views.py
> +                     "review_count":review_count}
코드 간격 맞춰주세요

2020-07-01 01:26 UTC, soheon-lee commented on partner/views.py
> +            prices_list = []
리스트 컴프리헨션으로 수정하셨다면 이 리스트는 사용되지 않습니다. 제거해주세요

2020-07-01 01:26 UTC, soheon-lee commented on partner/views.py
> +            [prices_list.append(price.price) for price in prices]
리스트 컴프리헨션 양식 수정해주세요.

2020-07-01 04:38 UTC, soheon-lee commented on partner/views.py
> +            prices_list= [price.price for price in prices]
코드 간격 맞춰주세요.

2020-07-01 07:43 UTC, evergreen-david requested changes

2020-07-01 07:43 UTC, evergreen-david commented on partner/views.py
> +            review_count = Review.objects.filter(history__in=partner.history_set.all()).count()
history_set 쿼리하는부분 for문 외부에서 캐쉬 부탁 드립니다. parter 가 많으면 성능상 문제가 생길수 있습니다.

2020-07-01 07:43 UTC, evergreen-david commented on partner/views.py
> +        partners = Counselor.objects.all()
Counselor 전부 가져오지말고 limit 제한 부탁 드립니다. Counselor 가 많아지면 성능상 문제가 생길수있습니다.

2020-07-01 07:43 UTC, evergreen-david commented on partner/views.py
> +
빈줄정리부탁드립니다.

2020-07-01 07:43 UTC, evergreen-david commented on partner/urls.py
> +
빈줄 정리 부탁드립니다.

2020-07-01 10:03 UTC, merged