signup, signin 및 signin decorate 기능 구현
wecode-bootcamp-korea/9-controst-backend pull request #5
Opened 2020-07-01 12:33 UTC by jayden0213

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
signup, signin 및 decorate 기능구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
1. signup 기능
 (1) 이메일 유효성 체크(RegexValidator와 정규식을 통해서 구현)
 (2) 비밀번호 유효성 체크(RegexValidator와 정규식을 통해서 구현)
 (3) 회원가입 기능 구현
 (4) bcrypt를 통한 비밀번호 암호화
 (5) 이메일 중복확인 버튼 기능
 (6) 닉네임 중복확인 버튼 기능
 (7) 닉네임 미입력시 랜덤 영문 닉넴임 생성

2. signin 기능
 (1) bcrypt를 통하여 비밀번호 복호화
 (2) jwt 토큰 발행

3. signin 데코레이터 구현

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [o] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [o] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [o] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [o] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-02 11:15 UTC, soheon-lee commented on trost/urls.py
> +   path('user/', include('user.urls'))
```suggestion
   path('user', include('user.urls'))
```

2020-07-02 11:15 UTC, soheon-lee commented on user/urls.py
> +from user.views import SignUpView, SignInView, HistoryView
```suggestion
from user.views import (
    SignUpView, 
    SignInView, 
    HistoryView
)
```

2020-07-02 11:16 UTC, soheon-lee commented on user/urls.py
> +   path('history', HistoryView.as_view()),
```suggestion
   path('/signup', SignUpView.as_view()),
   path('/signin', SignInView.as_view()),
   path('/history', HistoryView.as_view()),
```

2020-07-02 11:18 UTC, soheon-lee commented on user/views.py
> +import jwt
```suggestion
import bcrypt
import names
import json
import jwt

from django.http import JsonResponse, HttpResponse
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.views import View

from trost.settings import SECRET_KEY
from partner.models import (
    Counselor, 
    Product
)
from .models import (
    History, 
    User
)
from .models import User



```

2020-07-02 12:22 UTC, soheon-lee commented on user/views.py
> +                })
list comprehension으로 한 번 수정해주세요 👍

2020-07-02 12:23 UTC, soheon-lee commented on user/views.py
> +                    token=jwt.encode({"email":user_info.email}, SECRET_KEY, algorithm='HS256').decode('utf-8')
알고리즘 'HS256'이 노출되어 있습니다.
my_settings.py에 알고리즘을 변수화해서 숨겨주시고, 해당 파일에서 import 해서 사용해주세요.

2020-07-03 02:26 UTC, devops-andrew requested changes

2020-07-03 02:26 UTC, devops-andrew commented on trost/urls.py
> +   path('user/', include('user.urls'))
뒤에 / 남기게 되면 중간경로만 경로로 이용하게 될때 REST규칙에 어긋나게 되므로, 제거하고 하위 경로의 스트링 앞부분에 / 해주세요.

2020-07-03 02:26 UTC, devops-andrew commented on user/urls.py
> +]
경로앞에 / 처리해주세요.

2020-07-03 02:26 UTC, devops-andrew commented on user/views.py
> +import jwt
임포트 순서는 파이썬 라이브러리를 제일위에

장고모듈을 그다음에

사용자화된 클래스나 함수를 제일 나중에 간격 조정해서 배치해주세요.
아래 예시대로 해주시고 
종류별로 한줄씩 간격줘서 구분지어주세요.
```suggestion
import jwt

from django.http import JsonResponse, HttpResponse

from .models import History, User

```

2020-07-03 02:26 UTC, devops-andrew commented on user/views.py
> +        # regex of email address validation
이런 주석은 굳이 필요없습니다. 변수명이 말해주고 있어요

2020-07-03 02:26 UTC, devops-andrew commented on user/views.py
> +            except ValidationError:
이런식으로 한구간마다 try except 거는게 아니라, try 한번하고 try안에 정상로직이 끝나면 
아래쪽에 except 요소들만 걸면 됩니다.

2020-07-03 05:59 UTC, merged