Feature/map
wecode-bootcamp-korea/9-controst-backend pull request #6
Opened 2020-07-02 14:36 UTC by Einsicht1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
 map 앤드포인트 구현
    
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
map.models, map.views, map.urls 만듬.   

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ v] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ v] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ v] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-02 16:05 UTC, evergreen-david requested changes

2020-07-02 16:05 UTC, evergreen-david commented on map/models.py
> +# Create your models here.
주석 정리 부탁 드립니다.

2020-07-02 16:05 UTC, evergreen-david commented on map/models.py
> +        db_table = 'counselcenters'
```suggestion
        db_table = 'counsel_centers'
```

2020-07-02 16:05 UTC, evergreen-david commented on map/urls.py
> +        )
```suggestion
)
```

2020-07-02 16:05 UTC, evergreen-david commented on map/views.py
> +        )
리스트 컴프리헨션으로 수정을 부탁 드립니다.

2020-07-02 16:05 UTC, evergreen-david commented on partner/views.py
>                  )
이부분도 리스트컴프리헨션으로 수정하면 partners_list.append 하지않고 리스트를 만들수있습니다.

2020-07-02 16:05 UTC, evergreen-david commented on partner/views.py
> +             )
리스트 컴프리헨션에 관한 동일한 커멘트 입니다.

2020-07-03 01:45 UTC, Einsicht1 commented on partner/views.py
>                  )
상록님,
위 코드 list comprehension으로 바꿀 수 있는 건가요?
다시 살펴봤는데 문법상 어려워 보입니다.
for문 안에서  append만 실행되는게 아니라 그 전에 stars, review_count, prices 변수 선언을 먼저 하기 때문에 감이 잘 안오네요.
확인 부탁드립니다!

2020-07-03 06:00 UTC, soheon-lee commented
컨플릭트 해결해주세요

2020-07-03 06:18 UTC, merged